name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --recursive --remote

      - name: Install Dependencies
        run: npm install

      - name: Install nx globally
        run: npm install -g nx

      - name: Run e2e tests
        run: npx nx run e2e-stadtplan:e2e