name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
      - name: Update Submodules
        run: git submodule update --remote --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --recursive --remote

      - name: Install Dependencies
        run: npm install

      - name: Install nx globally
        run: npm install -g nx

      - name: Run smoke tests
        run: |
          npx nx run-many --target=e2e --testFile=smoke.cy.ts --skip-nx-cache